AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AWS::SSO::Assignment resource type

Globals:
  Function:
    Timeout: 60  # docker start-up times can be long for SAM CLI

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.sso.assignment.HandlerWrapper::handleRequest
      Runtime: java8
      CodeUri: ./target/aws-sso-assignment-1.0.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.sso.assignment.HandlerWrapper::testEntrypoint
      Runtime: java8
      CodeUri: ./target/aws-sso-assignment-1.0.jar
