language: java
dist: bionic
jdk: openjdk11
env:
  global:
    - PYENV_VERSION=3.7
    - AWS_REGION="us-east-1"
    - AWS_DEFAULT_REGION=$AWS_REGION
install:
  - pip3 install --user pre-commit cloudformation-cli-java-plugin
script:
  - pre-commit run --all-files --verbose
  - cd "$TRAVIS_BUILD_DIR/aws-sso-permissionset"
  # from Maven 3.6.1+, should use `--no-transfer-progress` instead of Slf4jMavenTransferListener
  - >
    mvn
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    -B
    clean verify
  - cd "$TRAVIS_BUILD_DIR/aws-sso-assignment"
  # from Maven 3.6.1+, should use `--no-transfer-progress` instead of Slf4jMavenTransferListener
  - >
    mvn
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    -B
    clean verify
  - cd "$TRAVIS_BUILD_DIR/aws-sso-instanceaccesscontrolattributeconfiguration"
  # from Maven 3.6.1+, should use `--no-transfer-progress` instead of Slf4jMavenTransferListener
  - >
    mvn
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    -B
    clean verify
after_failure:
  - cat "$TRAVIS_BUILD_DIR/aws-sso-permissionset/rpdk.log"
  - cat "$TRAVIS_BUILD_DIR/aws-sso-assignment/rpdk.log"
  - cat "$TRAVIS_BUILD_DIR/aws-sso-instanceaccesscontrolattributeconfiguration/rpdk.log"
